### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by SwiftKD** [lmachens/skeleton#15]
![Screenshot_1](https://user-images.githubusercontent.com/117479875/200060560-ee21e9a3-9ff5-498b-8bbd-fa177d3ed577.png)
I did do it multiple times restart my game launch overwolf first i do the exact same as my friend but for me it is just not working. Was working fine like 2 hours ago and then suddenly it won't connect anymore.

**Comment by lmachens** [comment]
Hi,please note that this is about Skeleton, not Aeternum Map.
Thus, better ask in the Discord of the app (Discord link in the app).

But to give you some help:
You need to make sure the screen capturing fallback is working.
Brightness and Contrast needs to be 5 and activate Show FPS ingame.
There are some other things you can try out, but please use the search on the Discord.
