### ISSUE TITLE
Skeleton Error on Route Management

### ISSUE THREAD

**Issue by Synthwave-Sun** [lmachens/skeleton#18]
Issue only occurs in Skeleton, not while using a generic browser (such as Microsoft Edge).

Steps to recreate:
1. Set up Overwolf, Aeternum Map for Overwolf, and Skeleton per provided instructions.
2. Open Routes panel by clicking 'Routes' button at top left of the Map in Skeleton.
3. Click 'Add Route' button.
4. Add at least two nodes.
5. Fill in the name in the Route Creation panel on the top right.
6. Click 'Save Route' button in the Route Creation panel on the top right.
7. Click on the route in the Routes panel on the left to open the 'Route Management' panel.
8. Observe error:
![image](https://user-images.githubusercontent.com/53713091/208919839-eed3ce07-8d69-40cf-8837-7f78735c6acc.png)

**Comment by lmachens** [comment]
Hi, please reset Skeleton and try again, there was a temporary issue. By the way, make sure to join the [Discord](https://discord.com/invite/NTZu8Px) for faster support :).

Skeleton related data is stored in:
%APPDATA%\skeleton

Close skeleton app
Open %APPDATA% in your explorer
Remove skeleton folder
Open Skeleton app
Feel free to reopen this or ask in Discord if this is not fixed.
