### ISSUE TITLE
Opacity 

### ISSUE THREAD

**Issue by 0ldi** [lmachens/skeleton#2]
1)Opacity setting, makes transparency whiter rather than transparent
2)Window title visible
![image](https://user-images.githubusercontent.com/16578229/145555196-88ff67ae-28ed-4b7d-92fb-18dc3f4d0ba9.png)

-and another question: is there a way not to show the minimap window when the game is not active

**Comment by ryselgh** [comment]
You have to uncheck "Frame" option and enable "Transparent" in the site settings

<img width="596" alt="image" src="https://user-images.githubusercontent.com/5698155/145556417-7cf079e8-5fbf-44d0-b7a9-f86cf255ba6c.png">

For the second question, you can disable "Always on top" to minimize the window, but it may disappear when in game. I recommend to leave that on and close the minimap when not needed, you can always reopen it without losing live position.

**Comment by 0ldi** [comment]
thanks it helped.
Is there a quick zoom change? in the game very often you have to change depending on the situation, and each time it is not very convenient to change these options
![image](https://user-images.githubusercontent.com/16578229/145563228-b2d0a0fc-5fc0-4bda-9a57-03d2ed9093fb.png)

and another thing that I do not understand, initially, these sizes correctly created frames, but then, if you change the numbers, nothing happens (even when you close and completely exit the app), but you can change the size like any Windows frame.
![image](https://user-images.githubusercontent.com/16578229/145561376-87a00cba-e636-43ae-8e01-c78d8d84c76b.png)

**Comment by lmachens** [comment]
@0ldi please see https://github.com/lmachens/aeternum-map/issues for Aeternum Map issues. There is a ticket for adaptive zoom levels.

The other issue about the width and height is correct, I will work on it :).

**Comment by 0ldi** [comment]
If I understood correctly, "Aeternum Map" is a completely legal add-on for overwold, and it does not show resources, and from there the current game coordinates are taken to synchronize with skeleton. I saw hotkeys for "Aeternum Map", and as I understand them for skeleton they are not yet available? In general, this is the only inconvenience so far, otherwise skeleton is amazing. Because the terrain is different, when you collect resources you need to see the map further, and when you collect chests in houses you get very close :)

**Comment by lmachens** [comment]
The thing is, these are two different projects.
Skeleton is not related to Aeternum Map, but you can open aeternum-map.gg (and every other website) in Skeleton. Skeleton is technically only a browser.
It's important that Skeleton is an independent project and has no connection to New World (to avoid ToS issues). 

I think the hotkeys you are referring to are related to https://github.com/lmachens/aeternum-map/releases/tag/v1.2.0-web.
This should work if you open aeternum-map.gg in Skeleton too, but make sure to login with steam.

**Comment by lmachens** [comment]
Width/Height issues are fixed in the latest version:
https://github.com/lmachens/skeleton/releases/tag/v1.3.0
