### ISSUE TITLE
Coordinates not refresh

### ISSUE THREAD

**Issue by 0ldi** [lmachens/skeleton#3]
my game was not responding, I closed the client and after that my coordinates in skeleton are not updated.
I've tried restarting everything, updated the skeleton to the latest version.
"Aeternum Map" shows coordinates, but sharing does not happen, I tried to change token and relogin in steam in both apps and skeleton not refresh new token, it not see it
When I try to insert a new token into Skeleton it is not saved there

![image](https://user-images.githubusercontent.com/16578229/147337955-71dec443-fd8c-48fe-951a-0c4f29ce6380.png)

re. hmmm. i click on EU server + sharing and its start working... nwm but maybe it help some1

**Comment by lmachens** [comment]
This is not related to Skeleton, it's related to Aeternum Map.
https://github.com/lmachens/aeternum-map

Please make sure to ask your question in Discord or in Aeternum Map repository.

Skeleton is independent of Aeternum Map.
