### ISSUE TITLE
Custom timers

### ISSUE THREAD

**Issue by 0ldi** [lmachens/skeleton#5]
I would like to suggest a feature, and this is how I see it:
I press Hotkey and your app records the current coordinates of my character (taken from the same Aeternum Map) and puts a Node with a timer on the map. You can set the timer time yourself, and for each hotkey. You need at least 3 different timers (for small medium and large resource size), and better more for other specific respawns.
-Ideally, the expiration of the timer has 2 phases: the first for start of resp, the second for end, because in NW dynamic respawn (for example 8min - 12min)
-Optional: the ability to select a sound when the timer expires

I must say right away that since all timers will be set manually when pressing hotkey, you can hardly see cheating here

**Comment by lmachens** [comment]
Hi, please see https://github.com/lmachens/aeternum-map/issues for Aeternum Map related issues.
Skeleton is not related to Aeternum Map, it's a tool to display any website as Overlay.
